### PR TITLE
initial submission for issue 22

### PR DESCRIPTION
**Pull request by neilchokriwala**
this is my initial submission for issue22.  I still need to run test cases

### CODE REVIEW

**Comment by jeffreytu** [comment]
You didn't remove the parted middleware from #27. So my POST to your instructors endpoint in explorer was hanging. Make sure that you do a pull origin master to upload your local.

**Comment by neilchokriwala** [comment]
i have functional code for this that is working now including the relational part, but i just need to create test

**Comment by treyhunner** [comment]
What command should I use to run the tests for this?

I tried:

    jasmine-node spec/api/

I see no output.  Is there something else I should be running?

**Comment by treyhunner** [comment]
Oh I missed your comment about tests. @neilchokriwala does that mean you haven't written tests for this yet?

**Comment by neilchokriwala** [comment]
yeah i need to add the tests.  I know it works.  I can do push, but have not written full detailed tests.

**Comment by goldlilys** [comment]
I tried running test:api for your instructors and I'm getting errors because you're including the course as properties in your tests. Remove any 'course' when posting a new record because that's separate from the instructors ... I mean it's a relation to a course, not part of it.

**Comment by neilchokriwala** [comment]
frances that change is in branch, I added it?

**Comment by goldlilys** [comment]
@neilchokriwala  would like to run gulp test:api then test:all for your branch, but it seems your gulpfile doesn't have those yet. Have you pull the new gulpfile from master yet?

**Comment by jeffreytu** [comment]
- make sure your master branch is updated locally and do a `git merge master` so you have a gulpfile we can run to test
- .gitignore still has a reference to neukinnis `neukinnis/server/datasources.local.json` 
- you might want to add some property checking in your instructors.js file. See the master's model for example
- cleanup instructors.spec of comments and maybe add a few more tests for property values
- make sure you move the fullstack in datasources.json into a datasources.local.json, leave only the memory connection in datasources.json
- can't test api in explorer due to not having a course module. put a mock course module just for testing purposes
- in instructor.json, "skills" might need to be an array so a person can put more than one skill

**Comment by goldlilys** [comment]
@jeffreytu  Oh, is skills supposed to be an array? I'm doing instructors for this week3-4 part and I'm using a string type . Hmm how would people enter that in a field ... using commas and that becomes an array?

**Comment by jeffreytu** [comment]
It was never discussed if it needed to be an array, but I just took it as needing to be an array because people should be able to enter more than one skill. People can just enter a comma seperated value in the input and just use jquery to split the string.

**Comment by goldlilys** [comment]
Included all of Neil's existing code with modifications on my  issue43_instructor branch, so this pull request does not need to be merged. Closing

**Pull request closed without merging**
